/** Color de acento por grupo terapéutico. El rojo NO se usa aquí: queda reservado a alertas y alto riesgo. */
export type ColorGrupo = 'naranjo' | 'violeta' | 'indigo' | 'azul' | 'turquesa' | 'verde' | 'ambar' | 'cian' | 'lima' | 'neutro'

const COLORES: Record<string, ColorGrupo> = {
  vasoactivo: 'naranjo',
  antiarritmico: 'violeta',
  antihipertensivo: 'violeta',
  diuretico: 'violeta',
  sedante: 'indigo',
  anticonvulsivante: 'indigo',
  antipsicotico: 'indigo',
  'analgesico-opioide': 'azul',
  'analgesico-no-opioide': 'azul',
  anestesico: 'turquesa',
  'bloqueador-neuromuscular': 'turquesa',
  antiemetico: 'lima',
  'protector-gastrico': 'lima',
  corticoide: 'lima',
  electrolito: 'verde',
  metabolico: 'verde',
  antibiotico: 'cian',
  'antiviral-antifungico': 'cian',
  antidoto: 'ambar',
  antihistaminico: 'ambar',
  anticolinergico: 'ambar',
  aine: 'azul',
  'relajante-muscular': 'turquesa',
  antigotoso: 'verde',
  antiparasitario: 'cian',
  antianginoso: 'violeta',
  hipolipemiante: 'violeta',
  digestivo: 'lima',
  antidiabetico: 'verde',
  hormonal: 'ambar',
  antidepresivo: 'indigo',
  'hipnotico-ansiolitico': 'indigo',
  'vitamina-mineral': 'verde',
}

export const colorGrupo = (grupo: string): ColorGrupo => COLORES[grupo] ?? 'neutro'
