export const AMBITOS: Record<string, string> = {
  samu: 'Prehospitalario',
  urgencia: 'Urgencia',
  upc: 'UPC',
  hospitalizacion: 'Hospitalización',
  aps: 'APS',
}

export const GRUPOS: Record<string, string> = {
  vasoactivo: 'Vasoactivos',
  antiarritmico: 'Antiarrítmicos',
  anticolinergico: 'Anticolinérgicos',
  sedante: 'Sedantes',
  'analgesico-opioide': 'Analgésicos opioides',
  anestesico: 'Anestésicos',
  electrolito: 'Electrolitos',
  'analgesico-no-opioide': 'Analgésicos no opioides',
  antidoto: 'Antídotos',
  antiemetico: 'Antieméticos',
  antihipertensivo: 'Antihipertensivos',
  antihistaminico: 'Antihistamínicos',
  antibiotico: 'Antibióticos',
  'antiviral-antifungico': 'Antivirales y antifúngicos',
  antipsicotico: 'Antipsicóticos',
  anticonvulsivante: 'Anticonvulsivantes',
  'bloqueador-neuromuscular': 'Bloqueadores neuromusculares',
  corticoide: 'Corticoides',
  diuretico: 'Diuréticos',
  hematologico: 'Hematológicos',
  metabolico: 'Metabólicos',
  'protector-gastrico': 'Protectores gástricos',
  aine: 'Antiinflamatorios (AINE)',
  'relajante-muscular': 'Relajantes musculares',
  antigotoso: 'Antigotosos',
  antiparasitario: 'Antiparasitarios',
  antianginoso: 'Antianginosos',
  hipolipemiante: 'Hipolipemiantes',
  digestivo: 'Digestivos',
  antidiabetico: 'Antidiabéticos',
  hormonal: 'Hormonales',
  antidepresivo: 'Antidepresivos',
  'hipnotico-ansiolitico': 'Hipnóticos y ansiolíticos',
  'vitamina-mineral': 'Vitaminas y minerales',
}

export const etiquetaGrupo = (g: string) => GRUPOS[g] ?? g
